# Generated by Django 5.2.13 on 2026-05-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(choices=[('sync_active_tenders', 'Sync Active'), ('enrich_tender', 'Enrich Tender'), ('embed_tender', 'Embed Tender'), ('cleanup_doc_chunks', 'Cleanup Chunks'), ('cleanup_old_documents', 'Cleanup Docs')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('ok', 'Ok'), ('partial', 'Partial'), ('failed', 'Failed')], max_length=10)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('stats', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-finished_at'],
                'indexes': [models.Index(fields=['task_name', 'finished_at'], name='alerts_pipe_task_na_5978bc_idx')],
            },
        ),
    ]
