# Generated by Django 5.2.13 on 2026-05-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_pipelinerun_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinerun',
            name='task_name',
            field=models.CharField(choices=[('sync_active_tenders', 'Sync Active'), ('enrich_tender', 'Enrich Tender'), ('embed_tender', 'Embed Tender'), ('cleanup_doc_chunks', 'Cleanup Chunks'), ('cleanup_old_documents', 'Cleanup Docs'), ('cleanup_finished_tenders', 'Cleanup Tenders'), ('recover_failed_tenders', 'Recover'), ('sync_komtender', 'Sync Komtender'), ('sync_tenderguru', 'Sync Tenderguru')], db_index=True, max_length=50),
        ),
    ]
