# Generated by Django 5.2.13 on 2026-04-29 14:04

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('okved_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, size=None)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('regions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('nmck_min', models.BigIntegerField(blank=True, null=True)),
                ('nmck_max', models.BigIntegerField(blank=True, null=True)),
                ('law_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, size=None)),
                ('hyde_texts', models.JSONField(blank=True, null=True)),
                ('profile_vector', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=1024)),
                ('content_hash', models.CharField(blank=True, max_length=16)),
                ('vector_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='users.companyprofile')),
            ],
            options={
                'verbose_name': 'Направление компании',
                'verbose_name_plural': 'Направления компании',
            },
        ),
    ]
