# Generated by Django 5.2.13 on 2026-05-04 14:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_companydirection'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydirection',
            name='procedure_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), blank=True, default=list, size=None),
        ),
    ]
