# Generated by Django 5.2.13 on 2026-05-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_active_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydirection',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='contract_security_budget',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='has_bank_guarantee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='platforms',
            field=models.JSONField(default=list),
        ),
    ]
