# Generated by Django 5.2.13 on 2026-05-18 18:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_company_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydirection',
            name='exclude_keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
