# Generated by Django 5.2.13 on 2026-06-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_move_won_tender_ids_to_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydirection',
            name='region_mode',
            field=models.CharField(choices=[('only', 'only'), ('boost', 'boost')], default='boost', max_length=10),
        ),
    ]
