# Generated by Django 5.2.13 on 2026-06-07 11:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_add_region_mode_to_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydirection',
            name='industries',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None),
        ),
    ]
