# Generated by Django 5.2.13 on 2026-06-14 08:54

from django.db import migrations


def backfill_email_verified(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(email_verified=False).update(email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_add_email_verified'),
    ]

    operations = [
        migrations.RunPython(backfill_email_verified, migrations.RunPython.noop),
    ]
