# Generated by Django 5.2.13 on 2026-05-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_subscription_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='interval',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('halfyearly', 'Half-Yearly'), ('yearly', 'Yearly')], max_length=10),
        ),
    ]
