# Generated by Django 5.2.13 on 2026-04-30 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenders', '0005_add_trading_platform_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('file_type', models.CharField(blank=True, max_length=20)),
                ('s3_key', models.CharField(max_length=1000, unique=True)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('archive_path', models.CharField(blank=True, max_length=1000)),
                ('parsed_text', models.TextField(blank=True)),
                ('is_scanned', models.BooleanField(default=False)),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=32)),
                ('parse_status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обработка'), ('done', 'Готово'), ('failed', 'Ошибка'), ('skipped', 'Пропущен'), ('cleaned', 'Очищен')], db_index=True, default='pending', max_length=12)),
                ('parse_error', models.TextField(blank=True)),
                ('content_priority', models.PositiveSmallIntegerField(default=99)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('parent_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='documents.tenderdocument')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tenders.tender')),
            ],
            options={
                'verbose_name': 'Документ тендера',
                'verbose_name_plural': 'Документы тендеров',
                'ordering': ['content_priority', 'filename'],
            },
        ),
    ]
