# Generated by Django 5.2.13 on 2026-05-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(db_index=True, max_length=12, unique=True)),
                ('name', models.CharField(blank=True, max_length=512)),
                ('full_name', models.CharField(blank=True, max_length=1000)),
                ('region', models.CharField(blank=True, max_length=200)),
                ('okved_main', models.CharField(blank=True, max_length=20)),
                ('okved_list', models.JSONField(default=list)),
                ('status', models.CharField(blank=True, max_length=64)),
                ('director_name', models.CharField(blank=True, max_length=256)),
                ('revenue_rub', models.BigIntegerField(blank=True, null=True)),
                ('profit_rub', models.BigIntegerField(blank=True, null=True)),
                ('revenue_year', models.IntegerField(blank=True, null=True)),
                ('employees_count', models.IntegerField(blank=True, null=True)),
                ('founded_date', models.CharField(blank=True, max_length=32)),
                ('licenses_count', models.IntegerField(blank=True, null=True)),
                ('licenses_summary', models.TextField(blank=True)),
                ('purchases_customer_count', models.IntegerField(blank=True, null=True)),
                ('purchases_customer_amount', models.BigIntegerField(blank=True, null=True)),
                ('purchases_supplier_count', models.IntegerField(blank=True, null=True)),
                ('arbitration_count', models.IntegerField(blank=True, null=True)),
                ('fssp_count', models.IntegerField(blank=True, null=True)),
                ('risk_indicators', models.JSONField(default=dict)),
                ('rusprofile_id', models.IntegerField(blank=True, null=True)),
                ('dadata_updated_at', models.DateTimeField(blank=True, null=True)),
                ('rusprofile_updated_at', models.DateTimeField(blank=True, null=True)),
                ('rusprofile_failed', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Профиль заказчика',
                'verbose_name_plural': 'Профили заказчиков',
                'indexes': [models.Index(fields=['rusprofile_updated_at'], name='customers_c_rusprof_2c7799_idx')],
            },
        ),
    ]
