# Generated by Django 5.2.13 on 2026-04-28 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('full_name', models.CharField(blank=True, max_length=1000)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.TextField()),
                ('nmck', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('okpd_codes', models.JSONField(default=list)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Активный'), ('finished', 'Завершён'), ('cancelled', 'Отменён')], db_index=True, default='active', max_length=20)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('raw_json', models.JSONField(default=dict)),
                ('ai_summary', models.TextField(blank=True)),
                ('embedding_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenders', to='tenders.customer')),
            ],
            options={
                'verbose_name': 'Тендер',
                'verbose_name_plural': 'Тендеры',
                'ordering': ['-published_at'],
            },
        ),
    ]
