# Generated by Django 5.2.13 on 2026-04-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='inn',
            field=models.CharField(blank=True, db_index=True, max_length=12),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('inn', ''), _negated=True), fields=('inn',), name='unique_non_empty_inn'),
        ),
    ]
