# Generated by Django 5.2.13 on 2026-04-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0002_alter_customer_inn_customer_unique_non_empty_inn'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='auction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='bid_security_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='bid_security_required',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='contract_security_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='law_type',
            field=models.CharField(blank=True, choices=[('44-ФЗ', '44-ФЗ'), ('223-ФЗ', '223-ФЗ'), ('615-ПП', '615-ПП')], db_index=True, max_length=10),
        ),
        migrations.AddField(
            model_name='tender',
            name='trading_platform',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
