# Generated by Django 5.2.13 on 2026-04-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0003_add_tender_procurement_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='contract_security_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
