# Generated by Django 5.2.13 on 2026-04-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0004_add_contract_security_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='trading_platform_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
