# Generated by Django 5.2.13 on 2026-05-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0005_add_trading_platform_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='docs_indexed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
