# Generated by Django 5.2.13 on 2026-05-04 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0006_add_docs_indexed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('studying', 'Изучаю'), ('preparing', 'Готовлю заявку'), ('submitted', 'Подал'), ('won', 'Выиграл'), ('lost', 'Проиграл')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_entries', to='tenders.tender')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pipeline-запись',
                'verbose_name_plural': 'Pipeline-записи',
                'unique_together': {('user', 'tender')},
            },
        ),
    ]
