# Generated by Django 5.2.13 on 2026-05-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0007_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='procedure_type',
            field=models.CharField(choices=[('auction', 'Электронный аукцион'), ('contest', 'Конкурс'), ('request_quotations', 'Запрос котировок'), ('request_proposals', 'Запрос предложений'), ('single_source', 'Единственный поставщик'), ('other', 'Иной')], db_index=True, default='other', max_length=25),
        ),
    ]
