# Generated by Django 5.2.13 on 2026-05-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0014_seed_prompt_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaryexperiment',
            name='actual_model',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
