# Generated by Django 5.2.13 on 2026-05-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0016_seed_chat_qa_v1'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='enriched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
