# Generated by Django 5.2.13 on 2026-05-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0017_add_enriched_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summaryexperiment',
            name='strategy',
            field=models.CharField(max_length=30),
        ),
    ]
