# Generated by Django 5.2.13 on 2026-05-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0017_add_enriched_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='inn',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
