# Generated by Django 5.2.13 on 2026-05-14 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0018_extend_strategy_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderSummaryV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.JSONField(default=dict)),
                ('step_metrics', models.JSONField(default=dict)),
                ('total_input_tokens', models.PositiveIntegerField(default=0)),
                ('total_output_tokens', models.PositiveIntegerField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('generation_time_ms', models.PositiveIntegerField(default=0)),
                ('model', models.CharField(default='deepseek-chat', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary_v2', to='tenders.tender')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
