# Generated by Django 5.2.13 on 2026-05-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0018_alter_customer_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='inn',
            field=models.CharField(blank=True, db_index=True, max_length=12),
        ),
    ]
