# Generated by Django 5.2.13 on 2026-05-14 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0019_add_tender_summary_v2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tendersummaryv2',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summaries_v2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tendersummaryv2',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries_v2', to='tenders.tender'),
        ),
        migrations.AlterUniqueTogether(
            name='tendersummaryv2',
            unique_together={('tender', 'user')},
        ),
    ]
