# Generated by Django 5.2.13 on 2026-05-14 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0019_alter_customer_inn'),
        ('tenders', '0020_tendersummaryv2_user_alter_tendersummaryv2_tender_and_more'),
    ]

    operations = [
    ]
