# Generated by Django 5.2.13 on 2026-05-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0022_alter_tender_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='source',
            field=models.CharField(choices=[('eis', 'ЕИС (zakupki.gov.ru)'), ('bidzaar', 'Bidzaar'), ('komtender', 'Komtender'), ('tenderguru', 'TenderGuru'), ('other', 'Другой источник')], db_index=True, default='eis', max_length=20),
        ),
    ]
