# Generated by Django 5.2.13 on 2026-05-25 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0023_alter_tender_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderpipeline',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('studying', 'Изучаю'), ('preparing', 'Готовлю заявку'), ('submitted', 'Подал'), ('won', 'Выиграл'), ('lost', 'Проиграл')], max_length=20),
        ),
        migrations.CreateModel(
            name='PipelineActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('created', 'Создано'), ('status_changed', 'Статус изменён'), ('comment_added', 'Комментарий')], max_length=30)),
                ('old_value', models.CharField(blank=True, max_length=100)),
                ('new_value', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tenders.tenderpipeline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tenders.tenderpipeline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
