# Generated by Django 5.2.13 on 2026-05-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0024_alter_tenderpipeline_status_pipelineactivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='content_quality',
            field=models.SmallIntegerField(db_index=True, default=0),
        ),
    ]
