# Generated by Django 5.2.13 on 2026-05-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0025_content_quality_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='docs_download_status',
            field=models.CharField(blank=True, choices=[('', 'Не начато'), ('downloading', 'Загрузка'), ('done', 'Готово'), ('no_docs', 'Нет документов'), ('failed', 'Ошибка')], default='', max_length=20),
        ),
    ]
