# Generated by Django 5.2.13 on 2026-06-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0027_add_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='industry',
            field=models.CharField(blank=True, choices=[('construction_materials', 'Стройматериалы'), ('construction_works', 'Строительные работы'), ('medicine', 'Медицина и фармацевтика'), ('it', 'IT и оргтехника'), ('food', 'Продовольствие'), ('equipment', 'Оборудование'), ('energy', 'Энергия и ГСМ'), ('chemistry', 'Химия'), ('paper', 'Бумага и полиграфия'), ('agriculture', 'Сельское хозяйство'), ('textile', 'Текстиль и одежда'), ('furniture', 'Мебель'), ('security', 'Охрана и безопасность'), ('vehicles', 'Транспортные средства'), ('transport', 'Транспорт и логистика'), ('education', 'Образование и наука'), ('mining', 'Добыча и металлургия'), ('finance', 'Финансы и страхование'), ('other_goods', 'Прочие товары'), ('other_services', 'Прочие услуги')], db_index=True, max_length=30),
        ),
    ]
